/* eslint-disable */
// Generated by Wrangler by running `wrangler types shared-backups-worker/worker-configuration.d.ts --config shared-backups-worker/wrangler.jsonc --env-interface SharedBackupsEnv --include-runtime false` (hash: d1834b473dd85aebbb8005fb27263127)
interface __BaseEnv_SharedBackupsEnv {
	UPLOAD_LIMITER: RateLimit;
	GITHUB_OWNER: "Zhengfu200";
	GITHUB_REPO: "Tongji_Health_Map_Backups";
	GITHUB_BRANCH: "main";
	ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,https://tongji-health-map-self.vercel.app";
	GITHUB_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_SharedBackupsEnv {}
}
interface SharedBackupsEnv extends __BaseEnv_SharedBackupsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_BRANCH" | "ALLOWED_ORIGINS" | "GITHUB_TOKEN">> {}
}
