/* eslint-disable */
// Generated by Wrangler by running `wrangler types shared-backups-worker/worker-configuration.d.ts --config shared-backups-worker/wrangler.jsonc --env-interface SharedBackupsEnv --include-runtime false` (hash: d720956c2ed0fb7f755742924e1b6c5d)
interface __BaseEnv_SharedBackupsEnv {
	BACKUPS_DB: D1Database;
	UPLOAD_LIMITER: RateLimit;
	UPYUN_BUCKET: "tongji-health-map";
	UPYUN_OPERATOR: "zhengfu202";
	ALLOWED_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173,https://tongji-health-map-self.vercel.app,https://tongji-health-map.pages.dev";
	UPYUN_PASSWORD: string;
	ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_SharedBackupsEnv {}
}
interface SharedBackupsEnv extends __BaseEnv_SharedBackupsEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UPYUN_BUCKET" | "UPYUN_OPERATOR" | "ALLOWED_ORIGINS" | "UPYUN_PASSWORD" | "ADMIN_TOKEN">> {}
}
